var data_items=[
    {"name":"","id":""}
]

var data_npcs = {
    "qi changfa"			: {"name" : "戚长发",		"loc" : 26,		"id" : "qi changfa"},
    "ku rong"				: {"name" : "枯荣大师",		"loc" : 657,	"id" : "ku rong"},
    "yideng dashi"			: {"name" : "一灯大师",		"loc" : 534,	"id" : "yideng dashi"},
    "yue nv"				: {"name" : "越女",			"loc" : 868,	"id" : "yue nv"},
    "wei yixiao"			: {"name" : "韦一笑",		"loc" : 2433,	"id" : "wei yixiao"},
    "zhou botong"			: {"name" : "周伯通",		"loc" : 779,	"id" : "zhou botong"},
    "mao shiba"			: {"name" : "茅十八",		"loc" : 52,		"id" : "mao shiba"},
    "zhu xi"				: {"name" : "朱熹",			"loc" : 60,		"id" : "zhu xi"},
    "lu ban"				: {"name" : "鲁班",			"loc" : 38,		"id" : "lu ban"},
    "gongtangcang guoshi"	: {"name" : "贡唐仓国师",	"loc" : 1262,	"id" : "gongtangcang guoshi"},
    "chu niang"			: {"name" : "厨娘",			"loc" : 697,	"id" : "chu niang"},
    "kuihua taijian"		: {"name" : "葵花太监",		"loc" : 1289,	"id" : "kuihua taijian"},
    "huang shang"			: {"name" : "黄裳",			"loc" : 577,	"id" : "huang shang"},
    "dugu qiubai"			: {"name" : "独孤求败",		"loc" : 1837,	"id" : "dugu qiubai"},
    "nanhai shenni"		: {"name" : "南海神尼",		"loc" : 1468,	"id" : "nanhai shenni"},
    "zuo quan"				: {"name" : "左全",			"loc" : 1927,	"id" : "zuo quan"},
    "liang zhanglao"		: {"name" : "梁长老",		"loc" : 1928,	"id" : "liang zhanglao"},
    "ma juwei"				: {"name" : "马俱为",		"loc" : 1928,	"id" : "ma juwei"},
    "hong qigong"			: {"name" : "洪七公",		"loc" : 1929,	"id" : "hong qigong"},
    "jian zhanglao"		: {"name" : "简长老",		"loc" : 1930,	"id" : "jian zhanglao"},
    "he bujing"			: {"name" : "何不净",		"loc" : 2315,	"id" : "he bujing"},
    "li sheng"				: {"name" : "黎生",			"loc" : 2354,	"id" : "li sheng"},
    "bai shijing"			: {"name" : "白世镜",		"loc" : 1932,	"id" : "bai shijing"},
    "ma dayuan"			: {"name" : "马大元",		"loc" : 2324,	"id" : "ma dayuan"},
    "yu hongxing"			: {"name" : "余洪兴",		"loc" : 2340,	"id" : "yu hongxing"},
    "li futou"				: {"name" : "李斧头",		"loc" : 2352,	"id" : "li futou"},
    "xi zhanglao"			: {"name" : "奚长老",		"loc" : 1740,	"id" : "xi zhanglao"},
    "lu youjiao"			: {"name" : "鲁有脚",		"loc" : 1740,	"id" : "lu youjiao"},
    "peng youjing"			: {"name" : "彭有敬",		"loc" : 1740,	"id" : "peng youjing"},
    "qiu wanjia"			: {"name" : "裘万家",		"loc" : 70,		"id" : "qiu wanjia"},
    "zhao gouer"			: {"name" : "赵狗儿",		"loc" : 73,		"id" : "zhao gouer"},
    "kuai huosan"			: {"name" : "快活三",		"loc" : 75,		"id" : "kuai huosan"},
    "jiang shangyou"		: {"name" : "江上游",		"loc" : 1456,	"id" : "jiang shangyou"},
    "mo bushou"			: {"name" : "莫不收",		"loc" : 1458,	"id" : "mo bushou"},
    "qu lingfeng"			: {"name" : "曲灵风",		"loc" : 1993,	"id" : "qu lingfeng"},
    "lu chengfeng"			: {"name" : "陆乘风",		"loc" : 1981,	"id" : "lu chengfeng"},
    "huang yaoshi"			: {"name" : "黄药师",		"loc" : 1990,	"id" : "huang yaoshi"},
    "hu fei"				: {"name" : "胡斐",			"loc" : 2356,	"id" : "hu fei"},
    "cheng lingsu"			: {"name" : "程灵素",		"loc" : 149,	"id" : "cheng lingsu"},
    "miao renfeng"			: {"name" : "苗人凤",		"loc" : 1093,	"id" : "miao renfeng"},
    "hu yizhi"				: {"name" : "胡逸之",		"loc" : 444,	"id" : "hu yizhi"},
    "ge lunbu"				: {"name" : "葛伦布",		"loc" : 1644,	"id" : "ge lunbu"},
    "jinlun fawang"		: {"name" : "金轮法王",		"loc" : 2145,	"id" : "jinlun fawang"},
    "jiumo zhi"			: {"name" : "鸠摩智",		"loc" : 2139,	"id" : "jiumo zhi"},
    "lingzhi shangren"		: {"name" : "灵智上人",		"loc" : 2147,	"id" : "lingzhi shangren"},
    "hong antong"			: {"name" : "洪安通",		"loc" : 2567,	"id" : "hong antong"},
    "su quan"				: {"name" : "苏荃",			"loc" : 2569,	"id" : "su quan"},
    "ouyang feng"			: {"name" : "欧阳锋",		"loc" : 2275,	"id" : "ouyang feng"},
    "ouyang ke"			: {"name" : "欧阳克",		"loc" : 22,		"id" : "ouyang ke"},
    "shan yong"			: {"name" : "善勇",			"loc" : 1638,	"id" : "shan yong"},
    "sheng di"				: {"name" : "胜谛",			"loc" : 1939,	"id" : "sheng di"},
    "bao xiang"			: {"name" : "宝象",			"loc" : 2125,	"id" : "bao xiang"},
    "xuedao laozu"			: {"name" : "血刀老祖",		"loc" : 2130,	"id" : "xuedao laozu"},
    "tianlang zi"			: {"name" : "天狼子",		"loc" : 1172,	"id" : "tianlang zi"},
    "ding chunqiu"			: {"name" : "丁春秋",		"loc" : 1168,	"id" : "ding chunqiu"},
    "caihua zi"			: {"name" : "采花子",		"loc" : 1170,	"id" : "caihua zi"},
    "a zi"					: {"name" : "阿紫",			"loc" : 1160,	"id" : "a zi"},
    "chuchen zi"			: {"name" : "出尘子",		"loc" : 1162,	"id" : "chuchen zi"},
    "shihou zi"			: {"name" : "狮吼子",		"loc" : 1158,	"id" : "shihou zi"},
    "duan zhengchun"		: {"name" : "段正淳",		"loc" : 2400,	"id" : "duan zhengchun"},
    "duan zhengming"		: {"name" : "段正明",		"loc" : 541,	"id" : "duan zhengming"},
    "dao baifeng"			: {"name" : "刀白凤",		"loc" : 504,	"id" : "dao baifeng"},
    "murong fu"			: {"name" : "慕容复",		"loc" : 2195,	"id" : "murong fu"},
    "murong bo"			: {"name" : "慕容博",		"loc" : 2197,	"id" : "murong bo"},
    "murong longcheng"		: {"name" : "慕容龙城",		"loc" : 1230,	"id" : "murong longcheng"},
    "yue buqun"			: {"name" : "岳不群",		"loc" : 2185,	"id" : "yue buqun"},
    "gao laozhe"			: {"name" : "高老者",		"loc" : 2183,	"id" : "gao laozhe"},
    "ai laozhe"			: {"name" : "矮老者",		"loc" : 2183,	"id" : "ai laozhe"},
    "linghu chong"			: {"name" : "令狐冲",		"loc" : 2554,	"id" : "linghu chong"},
    "yue wife"				: {"name" : "岳夫人",		"loc" : 2192,	"id" : "yue wife"},
    "feng buping"			: {"name" : "封不平",		"loc" : 2226,	"id" : "feng buping"},
    "mei jian"				: {"name" : "梅剑",			"loc" : 2012,	"id" : "mei jian"},
    "xu zhu"				: {"name" : "虚竹",			"loc" : 2013,	"id" : "xu zhu"},
    "zhuo bufan"			: {"name" : "卓不凡",		"loc" : 1165,	"id" : "zhuo bufan"},
    "miejue shitai"		: {"name" : "灭绝师太",		"loc" : 2070,	"id" : "miejue shitai"},
    "jingxian shitai"		: {"name" : "静闲师太",		"loc" : 2101,	"id" : "jingxian shitai"},
    "jingkong shitai"		: {"name" : "静空师太",		"loc" : 2110,	"id" : "jingkong shitai"},
    "jingjia shitai"		: {"name" : "静袈师太",		"loc" : 2061,	"id" : "jingjia shitai"},
    "jingxuan shitai"		: {"name" : "静玄师太",		"loc" : 2064,	"id" : "jingxuan shitai"},
    "jingxu shitai"		: {"name" : "静虚师太",		"loc" : 2068,	"id" : "jingxu shitai"},
    "jinghui shitai"		: {"name" : "静慧师太",		"loc" : 2097,	"id" : "jinghui shitai"},
    "jingzhen shitai"		: {"name" : "静真师太",		"loc" : 2068,	"id" : "jingzhen shitai"},
    "jingzhao shitai"		: {"name" : "静照师太",		"loc" : 2106,	"id" : "jingzhao shitai"},
    "li mingxia"			: {"name" : "李明霞",		"loc" : 2050,	"id" : "li mingxia"},
    "bei jinyi"			: {"name" : "贝锦仪",		"loc" : 2066,	"id" : "bei jinyi"},
    "zhou zhiruo"			: {"name" : "周芷若",		"loc" : 2418,	"id" : "zhou zhiruo"},
    "su mengqing"			: {"name" : "苏梦清",		"loc" : 2051,	"id" : "su mengqing"},
    "fang bilin"			: {"name" : "方碧琳",		"loc" : 2118,	"id" : "fang bilin"},
    "zhao lingzhu"			: {"name" : "赵林珠",		"loc" : 2051,	"id" : "zhao lingzhu"},
    "ji xiaofu"			: {"name" : "纪晓芙",		"loc" : 2065,	"id" : "ji xiaofu"},
    "yang guo"				: {"name" : "杨过",			"loc" : 1956,	"id" : "yang guo"},
    "long nv"				: {"name" : "小龙女",		"loc" : 1956,	"id" : "long nv"},
    "lin chaoying"			: {"name" : "林朝英",		"loc" : 1950,	"id" : "lin chaoying"},
    "feng asan"			: {"name" : "冯阿三",		"loc" : 1719,	"id" : "feng asan"},
    "su xinghe"			: {"name" : "苏星河",		"loc" : 1720,	"id" : "su xinghe"},
    "xue muhua"			: {"name" : "薛慕华",		"loc" : 1722,	"id" : "xue muhua"},
    "kang guangling"		: {"name" : "康广陵",		"loc" : 1724,	"id" : "kang guangling"},
    "xiaoyao zi"			: {"name" : "逍遥子",		"loc" : 1839,	"id" : "xiaoyao zi"},
    "guxu daozhang"		: {"name" : "谷虚道长",		"loc" : 1514,	"id" : "guxu daozhang"},
    "song yuanqiao"		: {"name" : "宋远桥",		"loc" : 1514,	"id" : "song yuanqiao"},
    "zhang cuishan"		: {"name" : "张翠山",		"loc" : 1477,	"id" : "zhang cuishan"},
    "yu lianzhou"			: {"name" : "俞莲舟",		"loc" : 2158,	"id" : "yu lianzhou"},
    "zhang sanfeng"		: {"name" : "张三丰",		"loc" : 2161,	"id" : "zhang sanfeng"},
    "yin liting"			: {"name" : "殷梨亭",		"loc" : 2153,	"id" : "yin liting"},
    "mo shenggu"			: {"name" : "莫声谷",		"loc" : 1512,	"id" : "mo shenggu"},
    "yu daiyan"			: {"name" : "俞岱岩",		"loc" : 2421,	"id" : "yu daiyan"},
    "zhang songxi"			: {"name" : "张松溪",		"loc" : 2154,	"id" : "zhang songxi"},
    "zhao zhijing"			: {"name" : "赵志敬",		"loc" : 779,	"id" : "zhao zhijing"},
    "chen zhiyi"			: {"name" : "陈志益",		"loc" : 742,	"id" : "chen zhiyi"},
    "yin zhiping"			: {"name" : "尹志平",		"loc" : 775,	"id" : "yin zhiping"},
    "zhang zhiguang"		: {"name" : "张志光",		"loc" : 2270,	"id" : "zhang zhiguang"},
    "cui zhifang"			: {"name" : "崔志方",		"loc" : 2229,	"id" : "cui zhifang"},
    "li zhichang"			: {"name" : "李志常",		"loc" : 2231,	"id" : "li zhichang"},
    "shen zhifan"			: {"name" : "申志凡",		"loc" : 2268,	"id" : "shen zhifan"},
    "cheng yaojia"			: {"name" : "程瑶迦",		"loc" : 2266,	"id" : "cheng yaojia"},
    "fang zhiqi"			: {"name" : "房志起",		"loc" : 2236,	"id" : "fang zhiqi"},
    "qi zhicheng"			: {"name" : "祁志诚",		"loc" : 2237,	"id" : "qi zhicheng"},
    "wang zhitan"			: {"name" : "王志坦",		"loc" : 2248,	"id" : "wang zhitan"},
    "ma yu"				: {"name" : "马钰",			"loc" : 2232,	"id" : "ma yu"},
    "qiu chuji"			: {"name" : "丘处机",		"loc" : 2236,	"id" : "qiu chuji"},
    "tan chuduan"			: {"name" : "谭处端",		"loc" : 2271,	"id" : "tan chuduan"},
    "liu chuxuan"			: {"name" : "刘处玄",		"loc" : 2249,	"id" : "liu chuxuan"},
    "wang chuyi"			: {"name" : "王处一",		"loc" : 2230,	"id" : "wang chuyi"},
    "hao datong"			: {"name" : "郝大通",		"loc" : 2269,	"id" : "hao datong"},
    "sun buer"				: {"name" : "孙不二",		"loc" : 2267,	"id" : "sun buer"},
    "wang chongyang"		: {"name" : "王重阳",		"loc" : 2259,	"id" : "wang chongyang"},
    "qingfa biqiu"			: {"name" : "清法比丘",		"loc" : 1136,	"id" : "qingfa biqiu"},
    "qingwei biqiu"		: {"name" : "清为比丘",		"loc" : 1137,	"id" : "qingwei biqiu"},
    "qingshan biqiu"		: {"name" : "清善比丘",		"loc" : 1849,	"id" : "qingshan biqiu"},
    "qingwen biqiu"		: {"name" : "清闻比丘",		"loc" : 1857,	"id" : "qingwen biqiu"},
    "qingxiao biqiu"		: {"name" : "清晓比丘",		"loc" : 1865,	"id" : "qingxiao biqiu"},
    "daoguo chanshi"		: {"name" : "道果禅师",		"loc" : 1846,	"id" : "daoguo chanshi"},
    "daopin chanshi"		: {"name" : "道品禅师",		"loc" : 1872,	"id" : "daopin chanshi"},
    "daocheng chanshi"		: {"name" : "道成禅师",		"loc" : 1904,	"id" : "daocheng chanshi"},
    "daojue chanshi"		: {"name" : "道觉禅师",		"loc" : 1901,	"id" : "daojue chanshi"},
    "huikong zunzhe"		: {"name" : "慧空尊者",		"loc" : 1870,	"id" : "huikong zunzhe"},
    "huiru zunzhe"			: {"name" : "慧如尊者",		"loc" : 1871,	"id" : "huiru zunzhe"},
    "huixu zunzhe"			: {"name" : "慧虚尊者",		"loc" : 1905,	"id" : "huixu zunzhe"},
    "huiming zunzhe"		: {"name" : "慧名尊者",		"loc" : 1911,	"id" : "huiming zunzhe"},
    "huihe zunzhe"			: {"name" : "慧合尊者",		"loc" : 1919,	"id" : "huihe zunzhe"},
    "huixiu zunzhe"		: {"name" : "慧修尊者",		"loc" : 1924,	"id" : "huixiu zunzhe"},
    "huise zunzhe"			: {"name" : "慧色尊者",		"loc" : 1923,	"id" : "huise zunzhe"},
    "huimjie zunzhe"		: {"name" : "慧洁尊者",		"loc" : 1910,	"id" : "huimjie zunzhe"},
    "chengxin luohan"		: {"name" : "澄信",			"loc" : 1893,	"id" : "chengxin luohan"},
    "chengyi luohan"		: {"name" : "澄意",			"loc" : 1897,	"id" : "chengyi luohan"},
    "chengsi luohan"		: {"name" : "澄思",			"loc" : 1896,	"id" : "chengsi luohan"},
    "chengshi luohan"		: {"name" : "澄识",			"loc" : 1895,	"id" : "chengshi luohan"},
    "chengzhi luohan"		: {"name" : "澄知",			"loc" : 1875,	"id" : "chengzhi luohan"},
    "chengxin luohan"		: {"name" : "澄信",			"loc" : 1893,	"id" : "chengxin luohan"},
    "chengling luohan"		: {"name" : "澄灵",			"loc" : 1892,	"id" : "chengling luohan"},
    "chengyu luohan"		: {"name" : "澄欲",			"loc" : 1891,	"id" : "chengyu luohan"},
    "chengshang luohan"	: {"name" : "澄尚",			"loc" : 1890,	"id" : "chengshang luohan"},
    "chengguan luohan"		: {"name" : "澄观",			"loc" : 1874,	"id" : "chengguan luohan"},
    "chengzhi luohan"		: {"name" : "澄知",			"loc" : 1875,	"id" : "chengzhi luohan"},
    "chengming luohan"		: {"name" : "澄明",			"loc" : 1876,	"id" : "chengming luohan"},
    "chengjing luohan"		: {"name" : "澄净",			"loc" : 1877,	"id" : "chengjing luohan"},
    "chengjian luohan"		: {"name" : "澄坚",			"loc" : 1878,	"id" : "chengjian luohan"},
    "chengxing luohan"		: {"name" : "澄行",			"loc" : 1879,	"id" : "chengxing luohan"},
    "chengji luohan"		: {"name" : "澄行",			"loc" : 1880,	"id" : "chengji luohan"},
    "chengmie luohan"		: {"name" : "澄灭",			"loc" : 1881,	"id" : "chengmie luohan"},
    "chenghe luohan"		: {"name" : "澄和",			"loc" : 1882,	"id" : "chenghe luohan"},
    "xuanji dashi"			: {"name" : "玄寂大师",		"loc" : 1925,	"id" : "xuanji dashi"},
    "xuannan dashi"		: {"name" : "玄难大师",		"loc" : 1894,	"id" : "xuannan dashi"},
    "xuanku dashi"			: {"name" : "玄苦大师",		"loc" : 1878,	"id" : "xuanku dashi"},
    "xuanci dashi"			: {"name" : "玄慈大师",		"loc" : 1887,	"id" : "xuanci dashi"},
    "kong jian"			: {"name" : "空见",			"loc" : 1871,	"id" : "kong jian"},
    "du e"					: {"name" : "渡厄",			"loc" : 2412,	"id" : "du e"},
    "du jie"				: {"name" : "渡劫",			"loc" : 2412,	"id" : "du jie"},
    "du nan"				: {"name" : "渡难",			"loc" : 2412,	"id" : "du nan"},
    "da mo"				: {"name" : "达摩老祖",		"loc" : 2438,	"id" : "da mo"},
    "zhao banshan"			: {"name" : "赵半山",		"loc" : 2305,	"id" : "zhao banshan"},
    "dubi shenni"			: {"name" : "独臂神尼",		"loc" : 1430,	"id" : "dubi shenni"},
    "feng mofeng"			: {"name" : "冯默风",		"loc" : 2555,	"id" : "feng mofeng"},
    "sheng di"				: {"name" : "胜谛",			"loc" : 1639,	"id" : "sheng di"},
    "chen jialuo"			: {"name" : "陈家洛",		"loc" : 2468,	"id" : "chen jialuo"},
    "shang jianming"		: {"name" : "商剑鸣",		"loc" : 1284,	"id" : "shang jianming"},
    "jin shi"				: {"name" : "金狮",			"loc" : 2741,	"id" : "jin shi"},
    "yin long"				: {"name" : "银龙",			"loc" : 2732,	"id" : "yin long"},
    "tong tuo"				: {"name" : "铜驼",			"loc" : 2744,	"id" : "tong tuo"},
    "tie yan"				: {"name" : "铁燕",			"loc" : 2737,	"id" : "tie yan"},
    "liu ruosong"			: {"name" : "柳若松",		"loc" : 2725,	"id" : "liu ruosong"}, 
    "fu hongxue"			: {"name" : "傅红雪",		"loc" : 2734,	"id" : "fu hongxue"},
    "guo jing"			: {"name" : "郭靖",		"loc" : 177,	"id" : "guo jing"},
    "wu qian"			: {"name" : "吴潜",		"loc" : 2850,	"id" : "wu qian"},
    "yu jie"			: {"name" : "余介",		"loc" : 2871,	"id" : "yu jie"},
    "fan tingzhao"			: {"name" : "范廷召",		"loc" : 2845,	"id" : "fan tingzhao"},
    "meng gong"			: {"name" : "孟珙",		"loc" : 2858,	"id" : "meng gong"},
    "ge huaimin"			: {"name" : "葛怀敏",		"loc" : 2861,	"id" : "ge huaimin"},
    "pan guangyu"			: {"name" : "潘光裕",		"loc" : 2862,	"id" : "pan guangyu"},
    "kong shouzheng"			: {"name" : "孔守正",		"loc" : 2875,	"id" : "kong shouzheng"},
    "gao hua"			: {"name" : "高化",		"loc" : 2876,	"id" : "gao hua"},
    "nan xian":{"name":"南贤","loc":1551,"id":"nan xian"}
   };

var data_locations=[
    {name:"聊天室",id:"chatroom","loc":2046},
    {name:"武庙三楼",id:"fuben","loc":2765},
    {name:"鳌拜 鳌府大厅",id:"ao bai","loc":1418},
    {name:"屠人场",id:"trc","loc":306},

]
   function alias_npc(name, line, wildcards){
    var wcs = VBArray(wildcards).toArray();
    var id=wcs[0]
    var npc=data_npcs[id]
    if (npc){
        goto(npc.loc);
    }else{
        world.Note("NPC "+id +" 没找到。")
    }
   }

   function list_loc(){
        var list=Userinput.newlist("请选择你的目标","选择你要前往的目标,可以进行模糊搜索",true)
        var loc_gift=world.GetVariable("loc_gift")
        if (loc_gift){
            list.append(loc_gift,"储藏室(gift) @"+loc_gift+" LOC")

        }
        for (var key in data_npcs) {
            var npc=data_npcs[key]
            list.append(npc.loc,npc.name+"("+npc.id+") @"+npc.loc+" NPC")
        }
        for (var key in data_locations) {
            var loc=data_locations[key]
            list.append(loc.loc,loc.name+"("+loc.id+")  @"+loc.loc+" LOC")
        }
        list.publish("callback_list_loc")
   }
   function callback_list_loc(name,id,code,data){
       if (code===0){
            goto(data);
       }
   }