//--------------------------------------------------------------------------------
var dgmap_path = {		// 地宫地图
"p302927" :{"enter" : 30,"leave" : 29,"lockroom1" : 80,"lockroom2" : 57,"lockroom3" : 27,"lockroom4" : 23, "path" : "ne|se|ne|se|ne|ns|ns|nse|se||ew|nw|sew|nw|sew|e|n|sw|ew||new|se|w|ne|sew|ew|n|nse|sew|e|w|nw|s|ew|new|nsew|se|w|ew|ew||n|nse|sw|w|w|w|n|sew|ew|n|ns|nsw|s|n|se|ne|nse|nsw|sw|n|nse|nse|ns|nse|nsew|sew|new|s||e|w|w|n|sw|ew|w|new|ns|s|new|s|ne|ns|ns|nsew|s|ew|||nw|ns|nsw|s|n|nsw|s|nw|s|"},
"p104976" :{"enter" : 10,"leave" : 49,"lockroom1" : 76,"lockroom2" : 34,"lockroom3" : 86,"lockroom4" : 21, "path" : "ne|ns|nse|se|ne|ns|se|ne|nse|s|ew|n|sw|new|sw|e|ew|ew|new|s|new|se|n|sw|n|nsw|nsew|sw|nw|se|w|w|n|ns|nse|s|nw|s|ne|sew||e|n|se|ew|||ne|sew|w||ew|e|new|sw||ne|sew|new|s|e|ew|nw|sew||n|sew|w|new|s|new|nsw|nse|nsw|ns|ns|sew|n|sw||new|s|w||n|ns|nsew|s|||w||||||w|||"},
"p08919" :{"enter" : 0,"leave" : 89,"lockroom1" : 65,"lockroom2" : 36,"lockroom3" : 24,"lockroom4" : 19, "path" : "ne|s||||||n|se|e|ew|||||||e|new|sw|new|ns|se|e|ne|s|n|nsw|nsw|se|w|ne|nsew|nsw|sw|n|se|e|ne|sew|n|sw|ew|n|nse|se|new|sew|ew|ew||e|ew|ne|sew|new|sew|ew|ew|ew||new|sew|ew|w|ew|w|nw|sew|ew||w|ew|ew|n|nsw|s|n|sew|ew|||ew|ew|e||n|nse|sw|ew|||nw|nsw|nsw|s|n|sw|n|sw"},
"p0795" :{"enter" : 0,"leave" : 79,"lockroom1" : 85,"lockroom2" : 45,"lockroom3" : 5,"lockroom4" : 11, "path" : "ne|nse|s|ne|nse|se|||||ew|nw|s|ew|w|w|n|se|||nw|ns|nse|sw|ne|ns|s|nw|nse|se|n|nse|nsew|ns|sw|n|nse|ns|sew|w||w|new|s|n|ns|sw|n|nsew|s||n|nsew|se|n|nse|ns|se|new|se|ne|nse|sw|new|nse|nsw|s|ew|ew|ew|w|new|se|w|w|n|nse|sew|ew|w|n|sw|ew|n|nse|nse|sew|new|nsew|se|n|ns|nsw|s|w|w|w|w|w|w"},
"p60979" :{"enter" : 60,"leave" : 9,"lockroom1" : 51,"lockroom2" : 79,"lockroom3" : 44,"lockroom4" : 55, "path" : "ne|ns|se|e|ne|nse|s|n|nse|se|ew|ne|sew|new|sw|nw|nse|se|w|ew|ew|w|new|nsew|s|ne|sw|new|s|ew|ew|e|w|new|se|w|n|nsew|s|ew|new|nsw|s|w|ew|e|e|new|nse|sew|new|nse|nse|se|w|nw|nsw|sw|w|ew|w|w|w|ew|e|e||e|n|sew||ne|nse|nsew|nsew|sew|e|nw|ns|sw||w|ew|w|w|new|nsw|s||||n|nsw|ns|s|nw|ns|s||"},
"p207947" :{"enter" : 20,"leave" : 79,"lockroom1" : 33,"lockroom2" : 84,"lockroom3" : 43,"lockroom4" : 47, "path" : "|n|nse|ns|ns|nse|nse|s|e||ne|s|ew|e|e|ew|w|e|nw|se|new|se|ew|ew|new|nsw|ns|nsew|nse|sew|w|ew|new|sw|nw|s|e|w|w|ew||new|nsew|ns|s|e|nw|nse|ns|sew||w|w||ne|nsw|nse|sew|n|sew||ne|ns|s|w||w|ew|ne|sew||ew|n|ns|nse|se|ne|sew|w|w|n|nsw|ns|nse|sew|new|sew|new|s|e|n|ns|ns|sw|w|w|w|nw|ns|sw"},
"p906997" :{"enter" : 90,"leave" : 69,"lockroom1" : 26,"lockroom2" : 43,"lockroom3" : 12,"lockroom4" : 97, "path" : "ne|nse|s|e|e|n|se|n|nse|s|w|new|ns|sew|new|s|ew|e|ew||ne|sw|e|ew|ew|n|nsw|nsw|sew||w||nw|nsw|nsw|ns|ns|se|ew|e|||n|se|e|e|e|new|nsew|sw||||ew|new|sw|new|sw|w|e|e||n|nsew|sw|n|nsew|ns|nse|sw|new|ns|se|nw|se|e|ew||nw|s|ew||nw|nse|sw|ew|ew|ne|nse|se|w|n|ns|nsw|ns|nsw|nsw|sw|w|w"},
"p207979" :{"enter" : 20,"leave" : 79,"lockroom1" : 66,"lockroom2" : 79,"lockroom3" : 97,"lockroom4" : 2, "path" : "e||ne|ns|s|n|ns|nse|s|e|new|ns|nsw|se|n|se|e|new|ns|sw|new|s|e|w|n|nsew|sew|new|ns|s|new|nse|sw|n|se|w|nw|nsew|nse|se|w|ew|e|n|sew|ne|ns|sw|w|ew|e|ew|nw|nse|nsew|sew|ne|ns|s|ew|new|nsew|s|w|ew|nw|sw|e|n|sew|w|nw|ns|se|new|nse|s|nw|nse|sew||n|nse|sew|ew|nw|s|e|ew|ew|||w|nw|nsw|ns|ns|sw|w|w"},
"p505919" :{"enter" : 50,"leave" : 59,"lockroom1" : 91,"lockroom2" : 94,"lockroom3" : 27,"lockroom4" : 19, "path" : "e|n|se|e|ne|se|n|se||e|ew|e|nw|nsew|sw|nw|nse|nsw|ns|sw|ew|new|s|w|n|ns|sew|ne|nse|s|new|nsw|s|e|e||nw|sw|new|se|ew|n|ns|nsew|nsew|ns|ns|nse|sw|ew|ew|n|nse|sew|new|nse|se|new|s|w|nw|se|ew|w|ew|w|w|w|||e|nw|nsew|se|new|s|||||new|nse|sw|ew|w||||||w|nw|s|nw|ns|ns|s|||"},
"p102945" :{"enter" : 10,"leave" : 29,"lockroom1" : 71,"lockroom2" : 81,"lockroom3" : 13,"lockroom4" : 45, "path" : "ne|se|e|e|e|ne|ns|se|ne|se|ew|ew|ew|nw|nsew|sw||nw|sew|ew|w|nw|nsw|se|ew|ne|s|n|sew|w||n|ns|nsw|nsew|nsew|s|e|w||||||w|nw|nse|nsw|s|||e|e||n|nse|sew|e|e|||new|nsw|nse|nse|sew|w|new|nsw|s|ne|sew|e|w|ew|w|e|new|ns|s|w|ew|nw|nse|nsw|nse|nsew|nsew|se|e||w|n|nsw|s|w|w|w|nw|sw"},
"p709928" :{"enter" : 70,"leave" : 99,"lockroom1" : 28,"lockroom2" : 1,"lockroom3" : 85,"lockroom4" : 78, "path" : "n|nse|se|n|nse|s|n|nse|ns|s|n|sw|nw|se|ew|ne|ns|nsew|nse|s||n|ns|nsw|nsew|sw|e|ew|ew||||||ew|n|nsw|sew|nw|s||||n|sew|ne|s|nw|ns|se|ne|nse|s|ne|nsew|nsew|s|e|e|ew|ew|nw|se|ew|w|ew|ne|nsw|nsw|sew|ew||ew|new|s|ew|ew|n|ns|sew|w|e|nw|nsew|s|ew|nw|s||ew||nw|ns|nsw|s|nw|ns|s||w"},
"p604949" :{"enter" : 60,"leave" : 49,"lockroom1" : 99,"lockroom2" : 53,"lockroom3" : 72,"lockroom4" : 49, "path" : "e|e|n|ns|nse|ns|nse|s|ne|se|new|nsw|nse|s|ew|n|sew|n|sew|ew|ew|e|w|e|ew|e|ew|ne|sw|ew|ew|new|s|new|nsw|sw|nw|nsew|s|ew|new|nsew|nse|nsew|se|e|e|new|s|ew|w|ew|w|ew|w|new|nsew|sw|n|sw|e|new|s|w|n|sw|nw|nse|nse|s|nw|nsew|se|e|e|ne|s|w|new|s|ne|sw|new|nsw|nsew|sw||e|w|e|w||w||nw|ns|ns|nsw|ns|sw"},
"p507966" :{"enter" : 50,"leave" : 79,"lockroom1" : 63,"lockroom2" : 73,"lockroom3" : 82,"lockroom4" : 66, "path" : "||ne|s|ne|nse|s|e|ne|se|n|ns|sew|ne|sw|ew|n|sew|ew|ew|e|n|sew|ew|ne|sew|n|nsew|sw|ew|new|nse|sew|ew|w|ew|ne|sew|ne|sew|ew|w|nw|nsew|s|nw|sew|ew|w|ew|w|ne|nse|sew|e||w|w|e|ew|n|sw|w|ew|ew|ne|ns|ns|nsew|sew|n|ns|nse|sew|nw|sew|||w|ew|n|ns|sew|w|n|nsew|ns|s||w|n|ns|sw||n|sw||||"},
"p09994" :{"enter" : 0,"leave" : 99,"lockroom1" : 2,"lockroom2" : 73,"lockroom3" : 60,"lockroom4" : 94, "path" : "ne|nse|ns|nse|s||n|ns|nse|s|w|ew|e|ew|n|se|e|n|sew|e|e|nw|sew|w||ew|ew|ne|nsw|sw|new|nse|nsw|ns|ns|nsew|nsew|nsw|nse|s|w|w|||n|sw|ew|e|nw|s|e||||||new|sew|ne|s|new|s||e||n|sw|new|nsw|se|ew|||nw|nse|s|ne|sw|n|sew|nw|se|n|ns|nsew|ns|nsw|se|ne|sew|n|nsw|ns|ns|nsw|ns|s|w|w|w"},
"p803969" :{"enter" : 80,"leave" : 39,"lockroom1" : 51,"lockroom2" : 86,"lockroom3" : 81,"lockroom4" : 69, "path" : "e|||||||e|ne|se|ew|||e||ne|s|new|sw|ew|new|s|e|ew|e|nw|se|ew||ew|nw|ns|nsew|nsew|nsew|s|new|sw|n|sew|n|nse|sw|ew|new|ns|nsew|s|ne|sew|n|nsw|s|ew|new|s|nw|s|ew|w|e|n|se|ew|nw|ns|ns|s|nw|se|ew|e|nw|nsew|nse|ns|nse|nse|s|ew|new|sw|e|ew|w|n|sew|nw|s|w|nw|ns|nsw|nsw|s|n|sw|||"},
"p907977" :{"enter" : 90,"leave" : 79,"lockroom1" : 75,"lockroom2" : 77,"lockroom3" : 74,"lockroom4" : 12, "path" : "ne|ns|nse|ns|se||||||ew|ne|sew|n|sew||||||w|w|w||nw|nse|nse|se|e||e|e|e|e|e|ew|ew|new|nsw|se|nw|nsw|nsew|sew|nw|sew|w|w|ne|sew|ne|ns|sw|new|ns|sew|e|e|w|ew|ew|n|nse|sew|e|new|nsw|sw|e|ew|ew|ne|sew|new|sew|new|s|ne|nsw|sew|ew|ew|w|ew|w|new|se|ew|n|sew|w|w|n|nsw|s|w|w|w|n|sw"},
"p704918" :{"enter" : 70,"leave" : 49,"lockroom1" : 84,"lockroom2" : 21,"lockroom3" : 24,"lockroom4" : 18, "path" : "|e|n|se|e||e|e|n|se|e|ew|n|sew|nw|ns|sew|ew|ne|sw|new|sew|e|new|nse|ns|sew|new|nsw|s|w|ew|ew|w|nw|s|nw|sew|ne|se|n|sew|nw|ns|ns|nse|nse|sw|ew|w|e|ew|e|||w|new|ns|nsew|s|ew|ew|new|s|e|e|ew|ne|nsw|s|nw|nsw|nsew|s|new|sw|ew|w|||e|ne|sew|ne|sw|ne|nsw|s|||nw|sw|nw|nsw|ns|nsw|ns|s||"},
"p403947" :{"enter" : 40,"leave" : 39,"lockroom1" : 52,"lockroom2" : 94,"lockroom3" : 47,"lockroom4" : 54, "path" : "e||n|nse|ns|se||ne|nse|se|new|s|ne|sw|ne|nsw|nse|sw|ew|w|nw|ns|nsew|s|nw|se|w|ne|sew|e||e|new|nse|se|w|e|ew|ew|ew|ne|nsw|sw|w|new|s|new|sw|new|sw|new|ns|nse|se|ew|n|sew|n|nsew|s|ew|n|sew|ew|new|s|w|n|nsw|se|new|s|ew|ew|w|||||w|new|se|ew|w||e|||||w|w|nw|ns|ns|nsw|s|||"},
"p503988" :{"enter" : 50,"leave" : 39,"lockroom1" : 64,"lockroom2" : 31,"lockroom3" : 73,"lockroom4" : 88, "path" : "|e|||||||||ne|sew||||||ne|se|e|w|ew|n|nse|s|ne|se|ew|new|sw|e|ew|ne|nsew|ns|sw|ew|ew|new|se|new|nsew|sw|new|s|e|ew|ew|w|w|ew|ew|ne|sw|n|nsw|nsw|nsw|nse|se|ew|w|nw|nse|ns|s|ne|ns|sw|ew|nw|s|n|nsw|s|n|sew|ne|se|ew|||||n|nse|sew|ew|new|sw|||||n|sw|w|w|w|"},
"p104969" :{"enter" : 10,"leave" : 49,"lockroom1" : 73,"lockroom2" : 55,"lockroom3" : 12,"lockroom4" : 69, "path" : "e|e|ne|s|n|nse|s|e|e|e|new|nsw|nsew|s|ne|nsew|nse|sew|new|sew|new|s|w|n|sew|w|w|new|sw|ew|ew|e|e|ne|nsew|ns|s|w|n|sew|new|nsew|nsew|sw|nw|s|n|ns|nse|sew|w|ew|new|ns|nse|se|n|ns|sew|ew|n|sw|nw|se|w|w|||ew|ew|n|se||new|s||||w|w|ne|nsw|ns|nsw|s||||||nw|s||||||||"}
	};
//--------------------------------------------------------------------------------
