
//--------------------------------------------------------------------------------
var xmmap_path = {	
"p303956" :{"enter" : 30,"quest_room" : 39,"rest_room" : 56, "path" : "e|ne|nse|s|e|e|e|e|||new|sw|ew|ne|nsw|sew|ew|nw|se||new|s|ew|w|n|sew|ew|n|sew|e|ew|e|ew||e|nw|sew|n|nsw|sew|new|sw|ew|e|ew|e|new|s|n|sew|nw|se|new|sw|ew|new|sew|n|ns|sew|ne|sw|ew|n|nsw|sew|ew||n|sew|w||ew|ne|nse|sew|w|e|e|ew|||ew|ew|ew|ew|e|new|sew|ew|||nw|sw|w|nw|nsw|sw|nw|sw"},
"p606998" :{"enter" : 60,"quest_room" : 69,"rest_room" : 98, "path" : "n|ns|se|ne|se|e||n|se|e|e|e|ew|ew|nw|nsew|s|e|nw|sew|nw|nsew|nsw|sw|e|nw|nse|nsw|se|ew|e|ew|e|e|ew|ne|sew|ne|nsew|sew|new|nsw|sw|ew|ew|w|ew|w|w|ew|new|nse|s|new|sw|e|nw|s|n|sew|w|new|ns|nsw|ns|nsw|nse|nse|s|w||new|nse|nse|se|n|sew|new|se||n|sew|w|w|ew|ne|sw|w|new|s|n|nsw|s|n|sw|nw|s|n|nsw|s"},
"p605918" :{"enter" : 60,"quest_room" : 59,"rest_room" : 14, "path" : "e|||n|nse|ns|ns|ns|se||new|s|n|nse|sew|n|ns|se|new|s|ew|e|n|sew|ew|n|nse|nsw|sw|e|nw|nsw|ns|sw|ew||nw|nse|nse|sew|e|ne|s||w||ne|sw|w|ew|new|nsw|s|e|||new|se|n|sew|new|s|ne|sw|n|se|ew|w|ne|sew|nw|nse|sw|ne|ns|nsew|sw|ne|sw|w|n|nsew|s|new|s|w|ne|sew||||nw|ns|nsw|s||w|nw|s|"},
"p04988" :{"enter" : 0,"quest_room" : 49,"rest_room" : 30, "path" : "e|ne|nse|se|ne|ns|se|e|ne|s|nw|sw|ew|nw|nsew|s|new|nsew|sw|e|e|n|sw|ne|sw|e|w|ew|ne|sw|nw|ns|se|w|ne|sw|n|nsew|nsw|s||e|ew|ne|sw|e|ne|sew|n|se|n|nsew|nsw|nsew|nse|nsew|sew|ew|e|ew|n|nsw|se|w|w|w|w|nw|nsew|sew|ne|nse|sw||||n|ns|sw|w|ew|new|s|||ne|ns|ns|ns|se|w|nw|ns|ns|ns|nsw|ns|s||w"},
"p905988" :{"enter" : 90,"quest_room" : 59,"rest_room" : 88, "path" : "|e|||||||||n|sew||||||n|nse|s|n|nsw|nse|nse|ns|ns|se|ne|nsw|se|e|e|w|w|e|e|new|nsw|s|w|nw|nsw|ns|ns|sew|new|nsew|s|||e|n|se|n|sew|ew|nw|s|n|se|nw|nse|sew|n|sew|nw|nse|ns|se|ew|n|sew|ew|ne|sew|ne|sw|e|new|sw|n|sew|nw|sw|new|nsew|ns|sew|ew||n|nsw|s|n|sw|w|n|sw|nw|s"},
"p02956" :{"enter" : 0,"quest_room" : 29,"rest_room" : 56, "path" : "ne|nse|ns|s|ne|ns|se|e|||ew|nw|nse|ns|nsw|se|new|nsw|s||w|ne|nsw|s|e|ew|new|ns|se|e||new|s|ne|sw|ew|new|s|new|sw||new|s|ew|e|w|new|s|new|s|e|new|ns|nsw|sew|n|nsew|s|w||new|nsw|se|e|w|n|sw||||ew|n|nsew|nsew|s||||||nw|se|w|ew|e|||||||nw|s|nw|nsw|s||||"},
"p80997" :{"enter" : 80,"quest_room" : 99,"rest_room" : 15, "path" : "|||||ne|s|ne|s|||e||||ew|n|nsew|ns|s|n|sew||||nw|nse|nsw|se|e||nw|se|n|ns|ns|nsw|s|ew|ew|e|n|nsw|ns|ns|se|n|nse|nsw|sw|new|ns|ns|nse|s|nw|se|ew|ne|s|new|se|ne|nsew|se|e|new|nsew|sew||w|w|ew|w|nw|nsew|sw|ew|w||e|ne|nsew|se|e|w||ew|ne|se|nw|sw|w|nw|sw|||nw|sw|w"},
"p704979" :{"enter" : 70,"quest_room" : 49,"rest_room" : 79, "path" : "n|se|e|e||ne|se|ne|nse|s|e|new|nsw|sew|n|sw|new|sw|new|s|new|sw||new|s||ew|e|nw|s|nw|s|n|sew|||new|sew|ne|se|n|ns|ns|nsw|nse|s|ew|nw|sw|ew|||ne|s|ew|e|ew|e|n|sw|ne|s|ew|n|nsw|nsew|nsw|nsw|s|e|new|ns|nsw|s|ne|nsew|s|ne|ns|sew|new|se|e|ne|sw|new|nse|sew|e|w|w|nw|nsw|sw|n|sw|w|nw|nsw|s"},
"p705919" :{"enter" : 70,"quest_room" : 59,"rest_room" : 4, "path" : "|n|se|e|ne|s|e|e|e|e|e|n|nsew|sew|new|nse|nsw|nsew|nsew|sew|new|s|w|nw|sew|nw|s|w|w|w|new|ns|s|e|new|s|n|nse|se||new|s|ne|sew|ew||e|ew|new|s|ew|e|ew|nw|nsew|s|new|sw|new|s|nw|nsw|sew|n|sew||new|se|w|e|e|e|ew|n|sew|ne|sw|ew|e|ew|ew|new|sw||nw|sw||new|nsw|sw|nw|nsw|s|||||nw|s|"},
"p609998" :{"enter" : 60,"quest_room" : 99,"rest_room" : 5, "path" : "e|n|ns|nse|ns|ns|s|ne|nse|se|nw|nse|s|ew|n|nse|ns|sew|w|ew|n|nsew|nse|nsew|s|w|ne|nsew|se|ew|n|sw|ew|w|n|ns|sw|ew|w|ew|e|ne|nsew|s|n|se|n|sew||ew|ew|ew|new|s|ne|sew|e|ew|n|sew|ew|ew|ew|e|ew|nw|sew|ew|n|sew|ew|ew|nw|nsw|sw|n|nsw|nsw|s|ew|ew|ew|ne|nse|s|e|e||e|ew|nw|nsw|sw|w||nw|nsw|ns|nsw|sw"},
"p03967" :{"enter" : 0,"quest_room" : 39,"rest_room" : 67, "path" : "n|ns|nse|se|ne|se|ne|ns|ns|se|n|nse|sw|new|sew|nw|nsew|nse|s|ew|n|nsw|s|ew|ew|e|ew|w|n|sew|ne|s|e|w|ew|nw|sw|n|nse|sw|ew|e|nw|ns|sew|e|e|n|sw||nw|sew|n|nse|nsw|nsew|nsew|nse|s||n|nsw|nse|sw|ne|sew|ew|nw|s|||ne|sew|e|ew|w|nw|s||||w|w|nw|sew|ne|s|||||||n|nsw|nsw|s|||"},
"p503935" :{"enter" : 50,"quest_room" : 39,"rest_room" : 85, "path" : "||e|ne|se|ne|se|e|||e|e|new|sew|new|sw|new|nsew|s|e|new|nsw|sew|w|w|n|sw|nw|ns|sew|w|n|nsew|nse|nse|nse|nse|ns|s|w|e|ne|sw|w|ew|ew|ew||||new|sw|ne|se|w|w|w||||new|nse|sew|new|nse|nse|ns|se|||w|w|ew|w|w|ew|ne|sw|||n|nse|sw||ne|sew|w|||||nw|s||w|nw|s|||"},
"p802938" :{"enter" : 80,"quest_room" : 29,"rest_room" : 38, "path" : "||n|nse|s|n|ns|nse|s|||n|se|nw|ns|ns|ns|sew|e|||n|nsew|ns|ns|se|e|ew|ew|e|n|nse|sw|ne|ns|sew|nw|nsw|sew|ew|ne|nsw|s|w|ne|nsew|nse|s|ew|ew|nw|ns|s||ew|ew|new|s|nw|sew|n|ns|nse|se|ew|ew|nw|se|e|ew|n|se|ew|new|sw|nw|s|ew|ew|ew|ne|sew|ew|nw|ns|ns|s|nw|sew|ew|w|nw|nsw|s||||n|nsw|sw"},
"p20698" :{"enter" : 20,"quest_room" : 69,"rest_room" : 72, "path" : "e||e|n|nse|s|ne|nse|ns|s|new|nse|nsw|nse|sw|n|sew|new|ns|se|w|new|s|ew|e|ne|sew|w|e|ew|ne|sw||nw|sew|w|ew|n|nsw|sew|new|ns|se|n|nsew|se|ew|ne|s|ew|w|e|w||w|new|sw|ew|e|ew|n|nsw|nse|se|n|nsew|nse|sw|new|sw|n|nse|sew|w|n|sew|nw|s|w||n|sw|nw|se||new|ns|s||||n|ns|nsw|ns|sw||||"},
"p90997822" :{"enter" : 90,"quest_room" : 99,"rest_room" : 22, "path" : "n|se|n|nse|ns|s|e|e|n|se|ne|nsw|se|ew|e|e|new|sw|n|sew|w|e|nw|nsew|nsw|nsew|nsw|s|e|ew|n|sew|n|nsew|s|nw|ns|ns|nsw|sew||nw|ns|sew|e|e|||n|sw|||e|new|nsw|nsw|s|e|e|e|n|ns|nsew|nsw|ns|s|n|sew|new|sw|e|n|nsew|nse|ns|s|ne|sew|new|s|new|nse|sew|new|ns|s|ew|ew|new|se|w|w|w|nw|ns|ns|sw|nw|sw|w"},
"p808918" :{"enter" : 80,"quest_room" : 89,"rest_room" : 23, "path" : "ne|nse|nse|se|n|se|ne|s|||ew|w|w|new|s|new|sw|n|se||nw|s||ew|n|sew|e|e|ew||ne|ns|nse|sew|e|new|sew|nw|sew||ew|n|sw|nw|nsw|sew|nw|se|new|s|new|ns|s||e|new|s|nw|sew||nw|s|e|e|new|nsw|s|n|sew||e|n|nsw|nsw|sew||n|ns|nsw|se|new|se|ne|se|ew|||n|ns|sw|w|nw|sw|nw|sw|||||"},
"p701949" :{"enter" : 70,"quest_room" : 19,"rest_room" : 92, "path" : "|n|nse|se|ne|nse|nse|se|ne|se|ne|nse|sw|nw|sew|ew|w|new|sw|w|w|new|s|ne|sew|w|n|nsew|ns|se|n|nsew|s|w|new|ns|se|w|n|sw||new|s|n|sew||w|n|ns|se||ew||e|w|n|se|n|nse|sew|n|nsew|nse|sew|e|n|sew|n|sew|w|ne|sw|w|new|nsw|ns|nsew|ns|sew||new|se|e|w|e||new|s|nw|s|w|nw|nsw|ns|sw|n|sw|||"},
"p909957" :{"enter" : 90,"quest_room" : 99,"rest_room" : 50, "path" : "n|se|e|n|nse|nse|s|ne|nse|s|ne|nsw|nsw|nse|sew|new|nse|sew|nw|se|w|e|e|ew|w|w|ew|new|s|ew|e|nw|nsw|nsew|s|e|ew|w|e|ew|ew|e|e|new|s|new|sw|e|new|sew|new|nsw|nsew|nsw|s|w|n|sew|w|ew|ew|n|nsew|s|n|nse|ns|nsw|ns|sew|w|ne|sew|||w|e||n|sew|ne|sw|w||||new|nse|ns|sew|nw|ns|s||n|ns|sw|nw|s|w"},
"p90997872" :{"enter" : 90,"quest_room" : 99,"rest_room" : 72, "path" : "|n|nse|ns|nse|ns|s|ne|s|||ne|sew|ne|nsw|se|ne|sew|n|se|ne|sew|ew|ew|e|new|sw|new|ns|sw|ew|w|w|ew|new|sw||nw|ns|se|new|nse|s|ew|w||||e|ew|ew|new|s|nw|nse|s|||new|sew|ew|w|ne|se|new|s|e|n|sew|ew|ew|ne|sw|w|w||nw|ns|sew|ew|new|nsew|nse|s|n|ns|ns|nse|sew|ew|w|w|nw|s|n|ns|ns|sw|w|w"},
"p605927" :{"enter" : 60,"quest_room" : 59,"rest_room" : 22, "path" : "e|ne|s|n|ns|se|ne|nse|nse|s|ew|ew|e||e|nw|sew|ew|w|e|new|nsew|nsw|ns|nsw|se|ew|nw|ns|sw|w|ew|n|ns|se|new|sw|e||||w|e|e|nw|sew|e|ew|e|e|e|n|nsw|sew|e|new|nsew|nsw|nsew|sew|nw|se|ne|nsew|sew|w|new|se|w|w|ne|sew|ew|w|new|ns|sw|new|nse|se|w|ew|new|s|new|s|n|sew|w|w||nw|nsw|s|nw|s|n|nsw|ns|s"},
"p405996" :{"enter" : 40,"quest_room" : 59,"rest_room" : 96, "path" : "n|nse|ns|nse|se|||||||w|ne|sw|new|s|e|e|n|se|n|nse|sw|e|new|s|ew|ew|e|ew|ne|sw|n|nsw|nsew|ns|nsew|nsw|nsew|sew|new|nse|nse|se|w|ne|nsw|se|ew|ew|ew|w|w|new|se|w|e|ew|w|ew|w|e|ne|sew|ew|ne|nsew|nsw|s|ew|n|nsw|sew|w|w|ew|nw|s|ne|sw|ne|ns|sew|ne|s|w|e|n|nsew|s|w|n|nsw|nsw|s|n|nsw|ns|nsw|s"}
	};
//--------------------------------------------------------------------------------