Metronome.settick(1100)
Metronome.setinterval(50)
world.DiscardQueue=function(){
    Metronome.discard()
}
world.queue=function(cmd,echo){
    Metronome.setbeats(world.GetVariable("num_cmds")/2)
    Metronome.push([cmd],false,echo)
}
world.LockQueue=function(){
    Metronome.lockqueue()
}